version: '3.8'

services:
  ga4-http-api:
    build: .
    container_name: ga4-http-api
    ports:
      - "${PORT:-8000}:8000"
    environment:
      # GA4 Configuration
      - GA4_PROPERTY_ID=${GA4_PROPERTY_ID}
      
      # Option 1: Use individual environment variables (recommended for Coolify)
      - GA4_PROJECT_ID=${GA4_PROJECT_ID}
      - GA4_PRIVATE_KEY_ID=${GA4_PRIVATE_KEY_ID}
      - GA4_PRIVATE_KEY=${GA4_PRIVATE_KEY}
      - GA4_CLIENT_EMAIL=${GA4_CLIENT_EMAIL}
      - GA4_CLIENT_ID=${GA4_CLIENT_ID}
      
      # Option 2: Use JSON file (set path if using file)
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS:-/app/credentials/ga4-service-account.json}
      
      # HTTP Server Configuration
      - PORT=${PORT:-8000}
      - HOST=${HOST:-0.0.0.0}
      - API_USERNAME=${API_USERNAME}
      - API_PASSWORD=${API_PASSWORD}
      
    volumes:
      # Only needed if using JSON file method
      - ./credentials:/app/credentials:ro
      
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/', timeout=10).raise_for_status()"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Original MCP server for Claude Desktop
  # ga4-mcp-server:
  #   build: .
  #   container_name: ga4-mcp-server
  #   command: ["python", "ga4_mcp_server.py"]
  #   environment:
  #     - GA4_PROPERTY_ID=${GA4_PROPERTY_ID}
  #     - GA4_PROJECT_ID=${GA4_PROJECT_ID}
  #     - GA4_PRIVATE_KEY_ID=${GA4_PRIVATE_KEY_ID}
  #     - GA4_PRIVATE_KEY=${GA4_PRIVATE_KEY}
  #     - GA4_CLIENT_EMAIL=${GA4_CLIENT_EMAIL}
  #     - GA4_CLIENT_ID=${GA4_CLIENT_ID}
  #   stdin_open: true
  #   tty: true
  #   restart: unless-stopped